### ISSUE TITLE
Please tag xorm and core together

### ISSUE THREAD

**Issue by aviau** [go-xorm/core#10]
Hello,

There is no rush, as we have already uploaded xorm and core to Debian, but it would help us if you tagged xorm and core so that they build together. I have ran into the issue that the last xorm tag did not build with the tip of core.

**Comment by lunny** [comment]
I have made the same tag v0.4.4 for xorm and core. Please try again. @aviau

**Comment by aviau** [comment]
I have fixed the problem before you tagged by uploading a non-tagged version of xorm. However, I thank you for tagging and I hope you will continue to do it as we will use it for future releases.

**Comment by lunny** [comment]
OKay. Thanks for your work.
